# Generated by Django 5.0.6 on 2024-06-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='gst_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='jurisdiction',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='license_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
