# Generated by Django 5.0.6 on 2024-06-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_add_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_stock',
            name='invice_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='add_stock',
            name='expiry_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
