# Generated by Django 5.0.6 on 2024-06-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Add_stock',
            new_name='add_stock',
        ),
    ]
