# Generated by Django 5.0.6 on 2024-06-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_rename_add_stock_cart_add_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
