# Generated by Django 5.0.6 on 2024-06-03 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_customer'),
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('1', 'Paid'), ('0', 'UnPaid')], default='0', max_length=50)),
                ('total_amount', models.FloatField(default=0, null=True)),
                ('order_filter', models.IntegerField(default=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.customer')),
                ('medical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sunil.medical')),
            ],
        ),
    ]
