# Generated by Django 5.0.6 on 2024-06-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_rename_order_master_ordermaster'),
        ('sunil', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderMaster',
            new_name='Order_Master',
        ),
    ]
