# Generated by Django 5.0.6 on 2024-06-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.AddField(
            model_name='cart',
            name='expiry_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='invice_number',
            field=models.IntegerField(null=True),
        ),
    ]
