# Generated by Django 5.0.6 on 2024-06-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_remove_cart_customer_cart_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='invice_number',
        ),
    ]
