# Generated by Django 5.0.6 on 2024-06-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_remove_cart_expiry_date_remove_cart_invice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='expiry_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='invice_number',
            field=models.IntegerField(null=True),
        ),
    ]
