# Generated by Django 5.0.6 on 2024-06-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0014_order_detail_expiry_date_order_detail_invice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
