# Generated by Django 5.0.6 on 2024-06-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0015_alter_customer_address_alter_customer_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
