# Generated by Django 5.0.6 on 2024-06-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0016_alter_customer_address_alter_customer_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
