# Generated by Django 5.0.6 on 2024-06-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0017_remove_item_image_remove_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_stock',
            name='add_qty',
        ),
        migrations.RemoveField(
            model_name='add_stock',
            name='item',
        ),
        migrations.RemoveField(
            model_name='add_stock',
            name='price',
        ),
        migrations.AddField(
            model_name='add_stock',
            name='batch_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_stock',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_stock',
            name='disc_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='add_stock',
            name='disc_qty_stripe',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='add_stock',
            name='disc_temp_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='add_stock',
            name='gst',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='add_stock',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_stock',
            name='item_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='add_stock',
            name='purchase_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='add_stock',
            name='qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='add_stock',
            name='qty_stripe',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='add_stock',
            name='sell_price_per_unit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='add_stock',
            name='temp_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='add_stock',
            name='total_purchase_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='add_stock',
            name='total_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='add_stock',
            name='expiry_date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='add_stock',
            name='invice_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
