# Generated by Django 5.0.6 on 2024-06-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0018_remove_add_stock_add_qty_remove_add_stock_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
