# Generated by Django 5.0.6 on 2024-06-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0019_item_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='add_stock',
            name='expiry_date',
            field=models.DateField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
