# Generated by Django 5.0.6 on 2024-06-10 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0021_customer_medical_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.doctor'),
        ),
        migrations.AddField(
            model_name='cart',
            name='sell_price_per_unit',
            field=models.FloatField(null=True),
        ),
    ]
