# Generated by Django 5.0.6 on 2024-06-12 03:39

import month.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0022_remove_cart_item_remove_cart_price_cart_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_stock',
            name='expiry_date',
            field=month.models.MonthField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
