# Generated by Django 5.0.6 on 2024-06-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0024_alter_add_stock_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_stock',
            name='parti_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
