# Generated by Django 5.0.6 on 2024-06-15 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0027_add_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_stock',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.item'),
        ),
        migrations.AddField(
            model_name='add_stock',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='owner.add_party'),
        ),
    ]
