# Generated by Django 5.0.6 on 2024-06-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0028_add_stock_item_add_stock_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_stock',
            old_name='parti_name',
            new_name='party_name',
        ),
    ]
