# Generated by Django 5.0.6 on 2024-06-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0029_rename_parti_name_add_stock_party_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='schedule_type',
            field=models.CharField(choices=[('0', 'Regular'), ('1', 'H1'), ('2', 'X')], max_length=100, null=True),
        ),
    ]
