# Generated by Django 5.0.6 on 2024-06-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0030_item_schedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='schedule_type',
            field=models.IntegerField(choices=[('0', 'Regular'), ('1', 'H1'), ('2', 'X')], null=True),
        ),
    ]
