# Generated by Django 5.0.6 on 2024-06-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0031_alter_item_schedule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='schedule_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('H1', 'H1'), ('X', 'X')], max_length=100, null=True),
        ),
    ]
