# Generated by Django 5.0.6 on 2024-06-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0034_remove_order_detail_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='doctor',
        ),
    ]
